import type { BadgeDef } from '../types';

export const BADGE_DEFINITIONS: BadgeDef[] = [
  {
    id: 'first_photo',
    name: 'Premier Souvenir',
    description: 'Capturer votre tout premier souvenir',
    icon: 'camera',
    condition: (ctx) => ctx.totalPhotos >= 1,
  },
  {
    id: 'streak_3',
    name: '3 jours',
    description: 'Serie de 3 jours consecutifs',
    icon: 'flame',
    condition: (ctx) => ctx.currentStreak >= 3,
  },
  {
    id: 'streak_7',
    name: 'Week Warrior',
    description: 'Serie de 7 jours consecutifs',
    icon: 'flame',
    condition: (ctx) => ctx.currentStreak >= 7,
  },
  {
    id: 'streak_30',
    name: 'Monthly Master',
    description: 'Serie de 30 jours consecutifs',
    icon: 'trophy',
    condition: (ctx) => ctx.currentStreak >= 30,
  },
  {
    id: 'streak_100',
    name: 'Centurion',
    description: 'Serie de 100 jours consecutifs',
    icon: 'medal',
    condition: (ctx) => ctx.currentStreak >= 100,
  },
  {
    id: 'streak_365',
    name: "Un An de Souvenirs",
    description: 'Serie de 365 jours consecutifs',
    icon: 'star',
    condition: (ctx) => ctx.currentStreak >= 365,
  },
  {
    id: 'photos_50',
    name: 'Demi-Siecle',
    description: '50 photos prises au total',
    icon: 'images',
    condition: (ctx) => ctx.totalPhotos >= 50,
  },
  {
    id: 'photos_100',
    name: 'Album Centenaire',
    description: '100 photos prises au total',
    icon: 'albums',
    condition: (ctx) => ctx.totalPhotos >= 100,
  },
  {
    id: 'early_bird',
    name: 'Leve-tot',
    description: 'Prendre une photo avant 7h du matin',
    icon: 'sunny',
    condition: (ctx) => ctx.photoHour !== null && ctx.photoHour < 7,
  },
  {
    id: 'night_owl',
    name: 'Noctambule',
    description: 'Prendre une photo apres 22h',
    icon: 'moon',
    condition: (ctx) => ctx.photoHour !== null && ctx.photoHour >= 22,
  },
  {
    id: 'challenge_5',
    name: 'Challenger',
    description: 'Completer 5 defis quotidiens',
    icon: 'ribbon',
    condition: (ctx) => ctx.challengesCompleted >= 5,
  },
  {
    id: 'challenge_20',
    name: 'Champion des Defis',
    description: 'Completer 20 defis quotidiens',
    icon: 'trophy',
    condition: (ctx) => ctx.challengesCompleted >= 20,
  },
  {
    id: 'globe_trotter',
    name: 'Globe Trotter',
    description: 'Photos dans 5 endroits differents',
    icon: 'earth',
    condition: (ctx) => ctx.uniqueLocations >= 5,
  },
  {
    id: 'home_sweet_home',
    name: 'Home Sweet Home',
    description: '30 photos geolocalisees',
    icon: 'home',
    condition: (ctx) => ctx.geolocatedPhotos >= 30,
  },
];
